version: "3.8"

services:
  app:
    image: golang:latest
    volumes:
      - .:$PWD
    working_dir: $PWD
    command: ["tail", "-f", "/dev/null"]

  db:
    image: postgres:12.10
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGPORT: $POSTGRES_PORT
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 2s
      retries: 5
    expose:
      - 5432
    command: ["postgres", "-c", "log_statement=all"]
